### ISSUE TITLE
'names' attribute [4] must be the same length as the vector [0]

### ISSUE THREAD

**Issue by thebamoor** [BillPetti/baseballr#164] opened 2020-06-26 03:26 UTC
`> data <- daily_batter_bref("2019-08-01", "2019-10-03") %>% head()`

`Data courtesy of Baseball-Reference.com. Please consider supporting Baseball-Reference by signing up for a Statehead account: https://stathead.com`

`Error in names(df) <- `\*vtmp\*` :`

 ` 'names' attribute [4] must be the same length as the vector [0]`

**Comment by BillPetti** [comment] 2020-06-26 12:52
Duplicate of #156. See comments for temporary solution.

**Closed by BillPetti** 2020-06-26 12:52 UTC
