### ISSUE TITLE
daily_pitcher_bref function returning an error

### ISSUE THREAD

**Issue by AngelClaudio** [BillPetti/baseballr#171] opened 2020-07-22 14:10 UTC
REPREX:

```
library(baseballr)

raw_pitcher_data <- daily_pitcher_bref("2019-03-01", "2019-10-01")`
```
I get the following error:

```
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 
Error in names(df) <- `*vtmp*` : 
  'names' attribute [4] must be the same length as the vector [0]
```

**Comment by BillPetti** [comment] 2020-07-22 14:51
Duplicate of #156

**Closed by BillPetti** 2020-07-22 14:51 UTC
